INSERT INTO channel (name, url, logo)  

VALUE 
('TF1 ', 'https://www.tf1.fr/', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/TF1_logo_1990.png'),
('France 2', 'https://www.france.tv/france-2/', 'https://upload.wikimedia.org/wikipedia/commons/3/33/France_2_logo.png'),
('France 3', 'https://www.france.tv/france-3/', 'http://cyril.bourreau.free.fr/Vectoriel/France3-2008.png'),
('Canal+', 'www.canalplus.fr/', 'https://www.freenews.fr/wp-content/uploads/2015/03/Logo-Canal-.png'),
('France 5 ', 'https://www.france.tv/france-5/', 'https://upload.wikimedia.org/wikipedia/commons/4/41/France_5_logo_antenne_%282008%29.png'),
('M6', 'https://www.6play.fr/m6', 'https://upload.wikimedia.org/wikipedia/en/a/a8/M6-tv-logo.png'),
('Arte', 'www.arte.tv/fr', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Arte-Logo.svg/2000px-Arte-Logo.svg.png'),
('C8', 'replay.c8.fr/', 'https://upload.wikimedia.org/wikipedia/fr/thumb/7/7a/C8_vector.svg/800px-C8_vector.svg.png'),
('W9', 'https://www.6play.fr/w9', 'https://upload.wikimedia.org/wikipedia/fr/archive/8/86/20140417175821%21W9_2010.png'),
('TMC ', 'https://www.tf1.fr/tmc', 'https://upload.wikimedia.org/wikipedia/fr/thumb/2/2e/TMC_new.svg/1024px-TMC_new.svg.png'),
('NT1', 'https://www.tf1.fr/nt1', 'https://upload.wikimedia.org/wikipedia/fr/thumb/8/83/NT1_2012.svg/1024px-NT1_2012.svg.png'),
('NRJ 12', 'www.nrj-play.fr/nrj12', 'https://upload.wikimedia.org/wikipedia/fr/archive/e/ea/20101226190303%21NRJ12.png'),
('Public Senat - LCP AN', 'https://www.publicsenat.fr', 'https://upload.wikimedia.org/wikipedia/fr/thumb/6/66/Public_S%C3%A9nat_Logo.svg/700px-Public_S%C3%A9nat_Logo.svg.png'),
('France 4', 'https://www.france.tv/france-4/', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/France_4_logo.png/363px-France_4_logo.png'),
('BFMTV', 'www.bfmtv.com/', 'https://upload.wikimedia.org/wikipedia/fr/thumb/f/f8/BFM_TV.svg/664px-BFM_TV.svg.png'),
('CNews', 'www.cnews.fr/', 'https://i0.wp.com/news-room.fr/wp-content/uploads/2016/06/CNEWS-2016.png'),
('CStar', 'www.cstar.fr/', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Canal_Star_logo.svg/640px-Canal_Star_logo.svg.png'),
('Gulli', 'www.gulli.fr/', 'https://upload.wikimedia.org/wikipedia/fr/thumb/c/c6/Gulli_2010_avril_logo.svg/1056px-Gulli_2010_avril_logo.svg.png'),
('France O', 'https://www.france.tv/france-o/', 'https://upload.wikimedia.org/wikipedia/fr/thumb/8/8a/France_%C3%94_logo_2008.svg/511px-France_%C3%94_logo_2008.svg.png'),
('HD1 ', 'https://www.tf1.fr/hd1', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Logo_HD1_2012.svg/510px-Logo_HD1_2012.svg.png'),
('6ter', 'https://www.6play.fr/6ter', 'https://upload.wikimedia.org/wikipedia/fr/archive/d/dd/20170305110619%21Logo_6ter.png'),
('Numero 23', 'www.numero23.fr/', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Num%C3%A9ro_23_logo.png/1024px-Num%C3%A9ro_23_logo.png'),
('RMC Decouverte', 'rmcdecouverte.bfmtv.com/', 'https://upload.wikimedia.org/wikipedia/fr/7/73/Logo_RMC_D%C3%A9couverte_2012.png'),
('Cherie 25 ', 'www.nrj-play.fr/cherie25', 'https://upload.wikimedia.org/wikipedia/fr/f/f0/Ch%C3%A9rie_25_logo_2015.svg');